/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

/**
 *
 * @author owner
 */
public class LOCPanel11 extends javax.swing.JPanel {

    /**
     * Creates new form LOCPanel
     */
    public LOCPanel11() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        locTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        locTable2 = new javax.swing.JTable();

        locTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Base", null, null},
                {"Deleted", null, null},
                {"Modified", null, null},
                {"Added", null, null}
            },
            new String [] {
                "Program Size", "Plan", "Actual"
            }
        ));
        jScrollPane1.setViewportView(locTable);

        locTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Reused", null, null, null},
                {"Total New and Changed", null, null, null},
                {"Total LOC", null, null, null},
                {"Total New Reused", null, null, null}
            },
            new String [] {
                "Program Size", "Plan", "Actual", "To Date"
            }
        ));
        jScrollPane2.setViewportView(locTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable locTable;
    private javax.swing.JTable locTable2;
    // End of variables declaration//GEN-END:variables
}
